<div class="social-facebooklikebox">

<div id="fb-root"></div>
<script>(function(d, s, id) {var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src =
"//connect.facebook.net/us_en/all.js#xfbml=1&appId=693918234369193";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</div>

<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="232" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="false"></div>